### ISSUE TITLE
cuda issues with selective_scan_cuda()

### ISSUE THREAD

**Issue by conze** [JiarunLiu/Swin-UMamba#20]
Hello, 
I have a cuda issue with selective_scan_cuda():
```
File "/usr/local/lib/python3.12/dist-packages/mamba_ssm/ops/selective_scan_interface.py", line 44, in forward
    out, x, *rest = selective_scan_cuda.fwd(u, delta, A, B, C, D, z, delta_bias, delta_softplus)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
Any idea to solve the problem? 
Thank you !

**Comment by luckypigg** [comment]
> Hello, I have a cuda issue with selective_scan_cuda():
> 
> ```
> File "/usr/local/lib/python3.12/dist-packages/mamba_ssm/ops/selective_scan_interface.py", line 44, in forward
>     out, x, *rest = selective_scan_cuda.fwd(u, delta, A, B, C, D, z, delta_bias, delta_softplus)
> RuntimeError: CUDA error: no kernel image is available for execution on the device
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> ```
> 
> Any idea to solve the problem? Thank you !

Hello，i got the same question.
Could you tell me if you have solved it or how？

**Comment by conze** [comment]
The problem is not solved. For info, I have a Nvidia 1080Ti GPU. 
I tried to use `selective_scan_easy` instead but the results are not correct. 
Any help ?

**Comment by luckypigg** [comment]
> The problem is not solved. For info, I have a Nvidia 1080Ti GPU. I tried to use `selective_scan_easy` instead but the results are not correct. Any help ?
Can't solve.
Wait for the author reply.

**Comment by conze** [comment]
Dear authors, any ideas to solve the issue 🤖 ?

**Comment by dipeshgyawali** [comment]
I think I had the similar issue earlier. selective_scan_cuda.so file not found. I installed cuda 11.8, pytorch 2.0.1, mamba 1.1.1, causal-conv1d 1.1.1, numpy 1.26.3 and was able to solve the issue.
